Initial implementation
93artur/SimpleBankApp pull request #1
Opened 2024-01-31 16:32 UTC by 93artur

2024-01-31 16:47 UTC, IgorTsalko requested changes

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +    List<Client> clients = new ArrayList<>();
Access modifier

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +    public void sentToClient(Client Sender, Client Recipient, int sum) {
Why "Sender" and "Recipient" field names stat with capital letter? Should started with small letter only

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +        int totalSender = Sender.getCount().getTotal();
totalSender -> senderAccount?
then rename field in Client class, total -> account

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +            int temp1 = totalSender - sum;
do not use "temp" field name, use meaningful names

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +            Sender.getCount().setTotal(temp1);
Because of you are using capital letter for naming "Sender" it looks like static call for getCount()

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +            int temp2 = Recipient.getCount().getTotal() + sum;
the same about variable name, do not use temp

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +            Sender.addCheck(getCurrentDateTime() + " списано " + sum);
addCheck() looks like add some validation or something like that. Use "bill" instead

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +            System.out.println("Операция прошла успешно! На счет клиента " + Recipient.getName() + " зачислено " + sum);
Do not use Russian!

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +
remove extra empty lines

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +
the same, why is there 2 lines?

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +
and here?

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +        bank.clients.add(new Client("Егор", new Count(900)));
Only English for now

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/Client.java
> +
only 1 empty line!

2024-01-31 16:47 UTC, IgorTsalko commented on src/main/java/com/arturobank/Client.java
> +    private List <String> checks = new ArrayList<>();
bills

2024-01-31 17:24 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +    public void sentToClient(Client Sender, Client Recipient, int sum) {
corrected

2024-01-31 17:30 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +        int totalSender = Sender.getCount().getTotal();
corrected

2024-01-31 17:32 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +            int temp1 = totalSender - sum;
corrected

2024-01-31 17:33 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +            Sender.getCount().setTotal(temp1);
corrected

2024-01-31 17:37 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +
corrected

2024-01-31 17:37 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +
corrected

2024-01-31 17:38 UTC, 93artur commented on src/main/java/com/arturobank/Client.java
> +
corrected

2024-01-31 17:39 UTC, 93artur commented on src/main/java/com/arturobank/Client.java
> +    private List <String> checks = new ArrayList<>();
corrected

2024-01-31 17:50 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +        bank.clients.add(new Client("Егор", new Count(900)));
done

2024-02-01 05:30 UTC, IgorTsalko reviewed
Almost good for this time, only fix small problems pls

2024-02-01 05:30 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +    public void sentToClient(Client sender, Client recipient, int sum) {
'send' not 'sent' -> check forms of English verbs

2024-02-01 05:30 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +            System.out.println("Operation was successfully completed! " + sum + " was credited to the account of " + recipient.getName());
'was credited to the account' -> 'was sent to the account'

2024-02-01 10:54 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +    public void sentToClient(Client sender, Client recipient, int sum) {
fixed

2024-02-01 10:56 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +            System.out.println("Operation was successfully completed! " + sum + " was credited to the account of " + recipient.getName());
fixed

2024-02-01 12:35 UTC, merged