Adjusting program to work with user input
93artur/SimpleBankApp pull request #2
Opened 2024-02-01 21:09 UTC by 93artur

2024-02-02 06:43 UTC, IgorTsalko requested changes

2024-02-02 06:43 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> -        bank.sendToClient(bank.clients.get(0), bank.clients.get(1), 355);
Leave bank initial set as it was.

2024-02-02 06:43 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +                    sender = new Client(senderName, new Count(1000));
Let's search users from the bank list, for both, sender and recipient. If There is no such user - error message

2024-02-02 14:47 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> -        bank.sendToClient(bank.clients.get(0), bank.clients.get(1), 355);
fixed

2024-02-02 18:43 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +                    sender = new Client(senderName, new Count(1000));
resolved

2024-02-02 18:58 UTC, IgorTsalko requested changes

2024-02-02 18:58 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +    public Client isThereUser(String name) {
What does this method really do?
1. it check that is there user with such name or not
2. if there is user - return it.
Read about "Single responsibility principle"!

And then think about Map<String, Client> - that contains all clients. How you will get user in this case? Wouldn't this be a better solution?
Don't forget to think about the best user's identifier

2024-02-02 19:00 UTC, IgorTsalko requested changes

2024-02-02 19:00 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +                        System.out.println("There is no such user");
let's show the invalid name that was entered in the error log

2024-02-02 19:39 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +                        System.out.println("There is no such user");
resolved

2024-02-03 08:06 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +    public Client isThereUser(String name) {
resolved

2024-02-03 09:02 UTC, IgorTsalko requested changes

2024-02-03 09:02 UTC, IgorTsalko commented on src/main/java/com/arturobank/ClientBase.java
> +        Client newClient = new Client(name, new Count(1000));
All your clients will have initial account with 1000? Good bank! Could I be a client, I want my 1000$

2024-02-03 09:02 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +                    if (bank.clientBase.containClient(senderName)) {
do you really need this check? Can you just get client and if it not null - do break

2024-02-03 09:12 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +    ClientBase clientBase = new ClientBase();
fixed

2024-02-03 09:14 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +        bank.sendToClient(bank.clientBase.getClient("Egor"), bank.clientBase.getClient("Katy"), 355);
it was a check. removed it

2024-02-03 09:33 UTC, 93artur commented on src/main/java/com/arturobank/ClientBase.java
> +        if (clientsOfBank.containsKey(name)){
i thought, because of modifier "private" in field "Map<String, Client> clientsOfBank" and it will be better for safety. 
fixed

2024-02-03 09:36 UTC, 93artur commented on src/main/java/com/arturobank/ClientBase.java
> +        Client newClient = new Client(name, new Count(1000));
resolved

2024-02-03 16:23 UTC, IgorTsalko reviewed
"fixed some small problems and corrected some methods" - this is not good name for commit.

2024-02-03 16:23 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +                    if (bank.clientBase.getClientsOfBank().containsKey(senderName)) {
sender = bank.clientBase.getClient(senderName);
if (sender == null) {
   break;
}

2024-02-03 17:16 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +                    if (bank.clientBase.getClientsOfBank().containsKey(senderName)) {
resolved

2024-02-03 17:38 UTC, IgorTsalko commented on src/main/java/com/arturobank/ArturoBank.java
> +            sender.getAccount().setAccount(senderAccount - sum);
Like this?
getAccount().setAccount)

2024-02-03 17:50 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +            sender.getAccount().setAccount(senderAccount - sum);
fixed

2024-02-03 18:40 UTC, IgorTsalko approved these changes

2024-02-03 18:42 UTC, merged