Authorization * changed work with commands * changed method of creati…
93artur/SimpleBankApp pull request #4
Opened 2024-02-07 08:12 UTC by 93artur

…ng new client * changed class Account to CountsBase * added new variable countNumber, that is used for transfer operation

2024-02-07 08:49 UTC, IgorTsalko requested changes

2024-02-07 09:27 UTC, 93artur commented on src/main/java/com/arturobank/CountsBase.java
> +        return (int) (Math.random() * ++max) + min;
read about collision. Got it. Resolved

2024-02-07 10:47 UTC, 93artur commented on src/main/java/com/arturobank/CountsBase.java
> +public class CountsBase {
resolved

2024-02-07 10:57 UTC, 93artur commented on src/main/java/com/arturobank/ClientBase.java
> +        ArrayList<Client> values = new ArrayList<>(clientsOfBank.values());
fixed

2024-02-07 12:24 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +                        bank.myClient = bank.clientBase.getClientByName(userName);
fixed

2024-02-07 12:26 UTC, 93artur commented on src/main/java/com/arturobank/ArturoBank.java
> +                System.out.println("You can't choose your account");
because i cant send money from my account to my account - checking it

2024-02-08 07:09 UTC, IgorTsalko approved these changes

2024-02-08 07:09 UTC, merged