refactoring * using command pattern * using switch
93artur/SimpleBankApp pull request #5
Opened 2024-02-21 09:32 UTC by 93artur

2024-02-23 13:26 UTC, IgorTsalko requested changes

2024-02-23 13:26 UTC, IgorTsalko commented on src/main/java/com/arturobank/clientservice/ArturoBank.java
> +    ClientBase clientBase = new ClientBase();
do not forget about access modifiers pls!

2024-02-23 13:26 UTC, IgorTsalko commented on src/main/java/com/arturobank/clientservice/ArturoBank.java
> +    public String getCurrentDateTime() {
where do you use this method?

2024-02-23 13:26 UTC, IgorTsalko commented on src/main/java/com/arturobank/viewlayer/ConsoleReader.java
> +    public boolean consistsOfLetters(String line) {
"reader" - but has public validation method

2024-02-23 13:26 UTC, IgorTsalko commented on src/main/java/com/arturobank/viewlayer/ConsoleReader.java
> +    public void showClientCommands() {
"reader" by responsible for showing. So now this is ConsoleReaderAndShower

2024-02-23 13:26 UTC, IgorTsalko commented on src/main/java/com/arturobank/viewlayer/ConsoleReader.java
> +    public void registerClient(BufferedReader reader, ClientOperation clientOperation, ClientBase
you do not use clientOperation

2024-02-23 13:26 UTC, IgorTsalko commented on src/main/java/com/arturobank/clientservice/ArturoBank.java
> +        commandNumber = consoleReader.chooseStartCommand(reader);
this is bad api! You don't have to send reader each time when you want to use consoleReader. Console reader have to have reader as a final field of the class

2024-02-23 13:26 UTC, IgorTsalko commented on src/main/java/com/arturobank/datebase/AccountBase.java
> +public class AccountBase {
this is really bad api!

2024-02-23 13:26 UTC, IgorTsalko commented on src/main/java/com/arturobank/datebase/ClientBase.java
> +public class ClientBase {
this is bad api! This is not api at all!

2024-02-29 10:00 UTC, 93artur commented on src/main/java/com/arturobank/clientservice/ArturoBank.java
> +    ClientBase clientBase = new ClientBase();
fixed

2024-02-29 10:27 UTC, 93artur commented on src/main/java/com/arturobank/clientservice/ArturoBank.java
> +    public String getCurrentDateTime() {
deleted it

2024-02-29 10:30 UTC, 93artur commented on src/main/java/com/arturobank/viewlayer/ConsoleReader.java
> +    public void registerClient(BufferedReader reader, ClientOperation clientOperation, ClientBase
fixed

2024-02-29 10:34 UTC, 93artur commented on src/main/java/com/arturobank/viewlayer/ConsoleReader.java
> +    public void showClientCommands() {
fixed

2024-03-04 07:57 UTC, 93artur commented on src/main/java/com/arturobank/viewlayer/ConsoleReader.java
> +    public boolean consistsOfLetters(String line) {
fixed

2024-03-23 17:12 UTC, 93artur commented on src/main/java/com/arturobank/datebase/AccountBase.java
> +public class AccountBase {
fixed

2024-03-23 17:12 UTC, 93artur commented on src/main/java/com/arturobank/datebase/ClientBase.java
> +public class ClientBase {
resolved

2024-03-24 06:42 UTC, IgorTsalko requested changes

2024-03-24 06:42 UTC, IgorTsalko commented on src/main/java/com/arturobank/viewlayer/ConsoleController.java
> +package com.arturobank.viewlayer;
just view, not viewlayer

2024-03-24 06:42 UTC, IgorTsalko commented on src/main/java/com/arturobank/datebase/ClientBaseImpl.java
> +package com.arturobank.datebase;
this is "repository" layer

2024-03-24 06:42 UTC, IgorTsalko commented on src/main/java/com/arturobank/datebase/ClientBaseImpl.java
> +        return client;
why do you need such hard logic? You have map with key as a accountNumber - then just get by key from the map
return clientsOfBank.get(key);

2024-03-24 06:42 UTC, IgorTsalko commented on src/main/java/com/arturobank/datebase/ClientBaseImpl.java
> +        return client;
the same

2024-03-24 07:03 UTC, 93artur commented on src/main/java/com/arturobank/viewlayer/ConsoleController.java
> +package com.arturobank.viewlayer;
fied

2024-03-24 07:04 UTC, 93artur commented on src/main/java/com/arturobank/datebase/ClientBaseImpl.java
> +package com.arturobank.datebase;
fixed

2024-03-24 07:09 UTC, 93artur commented on src/main/java/com/arturobank/datebase/ClientBaseImpl.java
> +        return client;
resolved

2024-04-05 17:02 UTC, 93artur commented on src/main/java/com/arturobank/datebase/ClientBaseImpl.java
> +        return client;
fixed

2024-04-05 17:02 UTC, merged